### ISSUE TITLE
Error: Class "TomatoPHP\FilamentTranslationComponent\Components\Translation" not found

### ISSUE THREAD

**Issue by mailnike** [tomatophp/filament-subscriptions#1]
Hi, 

I am getting error when I did installation for the new project, URL: https://example.test/admin/plans/create : Class "TomatoPHP\FilamentTranslationComponent\Components\Translation" not found

<img width="993" alt="image" src="https://github.com/user-attachments/assets/f57eef62-480a-4c9b-b9d0-17aa75ed22a0">

**Comment by megoxv** [comment]
fixed in v1.0.3
