### ISSUE TITLE
Languages in plugin

### ISSUE THREAD

**Issue by ejjaquet** [tomatophp/filament-subscriptions#11]
Hi! I am trying out this plugin in my project, but I have a hard time trying to understand how it works. For the translation. I want to use only two languages, Dutch and English. But where do I configure to not use the Arabic, Portugese and Burmese, but English and Dutch?

**Comment by ejjaquet** [comment]
Never mind, I found it.

**Comment by fadymondy** [comment]
it's just translation component you need to change languages on it's config
