### ISSUE TITLE
Class "TomatoPHP\FilamentSubscriptions\Providers\FilamentSubscriptionsProvider" not found

### ISSUE THREAD

**Issue by HumanX-Life** [tomatophp/filament-subscriptions#2]
Hi, I'm getting `Class "TomatoPHP\FilamentSubscriptions\Providers\FilamentSubscriptionsProvider" not found` when I call:
```
use TomatoPHP\FilamentSubscriptions\Providers\FilamentSubscriptionsProvider;

->tenantBillingProvider(new FilamentSubscriptionsProvider())
```

![Screenshot 2024-09-05 at 23 13 59](https://github.com/user-attachments/assets/ced9f2d2-148e-4b10-96dd-dd3f4af56faf)

And, if I remove `Providers`, the error goes away, but I get `ERR_TOO_MANY_REDIRECTS ` after navigating to `https://example.test/app/3/billing`

![Screenshot 2024-09-05 at 23 13 25](https://github.com/user-attachments/assets/3ec16feb-4ef0-40f1-9224-eaca906c5e55)

**Comment by fadymondy** [comment]
your plugin version, please?

**Comment by HumanX-Life** [comment]
`v.1.0.2`. I have `"tomatophp/filament-subscriptions": "^1.0.2"` in my `composer.json` and using `Filament 3.x` and `Laravel 11.x`

I also see the latest version is `v.1.0.3` but I get 
```
  Problem 1
    - Root composer.json requires tomatophp/filament-subscriptions ^1.0.3, found tomatophp/filament-subscriptions[dev-master, v1.0.0, v1.0.1, v1.0.2] but it does not match the constraint.
```

The error `Class "TomatoPHP\FilamentSubscriptions\Providers\FilamentSubscriptionsProvider" not found` persists even if I try all other versions, `"dev-master", "1.0.1", or "1.0.0"`  in `composer.json`

**Comment by fadymondy** [comment]
it was a docs problem just remove `Providers` from the namespace
