### ISSUE TITLE
Trait "Filament\Pages\Concerns\HasMaxWidth" not found

### ISSUE THREAD

**Issue by unlucas22** [tomatophp/filament-subscriptions#5]
Hi,

I am getting error when I did installation for the new project, Symfony\Component\ErrorHandler\Error\FatalError at vendor/tomatophp/filament-subscriptions/src/Filament/Pages/Billing.php:28

![Captura de pantalla de 2024-09-07 12-55-23](https://github.com/user-attachments/assets/8630c6a1-f065-47fa-bd24-2964f13ba02b)

"php": "^8.2",
"laravel/framework": "^11.9",
"filament/filament": "3.2.57",
"tomatophp/filament-subscriptions": "v1.0.2",

**Comment by fadymondy** [comment]
check the new version please
