### ISSUE TITLE
Failed Install

### ISSUE THREAD

**Issue by ophaant** [tomatophp/filament-subscriptions#9]
Hello, I have a problem installing this plugin. i am using laravel 11 and filament 3. Please help.
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/e9541a6e-7460-4331-b4bc-13d2c45494f7">

**Comment by fadymondy** [comment]
you just need to run this

```bash
php artisan vendor:publish --provider="Laravelcm\Subscriptions\SubscriptionServiceProvider"
```

please follow install docs

**Comment by ophaant** [comment]
<img width="1296" alt="image" src="https://github.com/user-attachments/assets/cedab38c-3766-45e8-ab90-a7e7b3bbc396">

what's worng?
